/// One Browser Use managed-proxy location.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ProviderProxyLocation {
    pub code: &'static str,
    pub name: &'static str,
}

/// Version-pinned snapshot of Browser Use API v3's `proxyCountryCode` enum.
///
/// Browser Use does not publish a location-discovery endpoint. Keep this exact provider enum
/// (rather than an ISO-country library) because it intentionally contains aliases such as `uk`
/// and `xk`, legacy codes such as `an` and `cs`, and omits some ISO codes. Snapshot verified
/// against the v3 create-browser schema on 2026-09-04.
pub const BROWSER_USE_PROXY_SCHEMA_SNAPSHOT: &str = "browser-use-api-v3@2026-09-04";

pub const BROWSER_USE_PROXY_LOCATIONS: &[ProviderProxyLocation] = &[
    ProviderProxyLocation { code: "ad", name: "Andorra" },
    ProviderProxyLocation { code: "ae", name: "United Arab Emirates" },
    ProviderProxyLocation { code: "af", name: "Afghanistan" },
    ProviderProxyLocation { code: "ag", name: "Antigua & Barbuda" },
    ProviderProxyLocation { code: "ai", name: "Anguilla" },
    ProviderProxyLocation { code: "al", name: "Albania" },
    ProviderProxyLocation { code: "am", name: "Armenia" },
    ProviderProxyLocation { code: "an", name: "Netherlands Antilles" },
    ProviderProxyLocation { code: "ao", name: "Angola" },
    ProviderProxyLocation { code: "aq", name: "Antarctica" },
    ProviderProxyLocation { code: "ar", name: "Argentina" },
    ProviderProxyLocation { code: "as", name: "American Samoa" },
    ProviderProxyLocation { code: "at", name: "Austria" },
    ProviderProxyLocation { code: "au", name: "Australia" },
    ProviderProxyLocation { code: "aw", name: "Aruba" },
    ProviderProxyLocation { code: "az", name: "Azerbaijan" },
    ProviderProxyLocation { code: "ba", name: "Bosnia & Herzegovina" },
    ProviderProxyLocation { code: "bb", name: "Barbados" },
    ProviderProxyLocation { code: "bd", name: "Bangladesh" },
    ProviderProxyLocation { code: "be", name: "Belgium" },
    ProviderProxyLocation { code: "bf", name: "Burkina Faso" },
    ProviderProxyLocation { code: "bg", name: "Bulgaria" },
    ProviderProxyLocation { code: "bh", name: "Bahrain" },
    ProviderProxyLocation { code: "bi", name: "Burundi" },
    ProviderProxyLocation { code: "bj", name: "Benin" },
    ProviderProxyLocation { code: "bl", name: "Saint Barthélemy" },
    ProviderProxyLocation { code: "bm", name: "Bermuda" },
    ProviderProxyLocation { code: "bn", name: "Brunei" },
    ProviderProxyLocation { code: "bo", name: "Bolivia" },
    ProviderProxyLocation { code: "bq", name: "Caribbean Netherlands" },
    ProviderProxyLocation { code: "br", name: "Brazil" },
    ProviderProxyLocation { code: "bs", name: "Bahamas" },
    ProviderProxyLocation { code: "bt", name: "Bhutan" },
    ProviderProxyLocation { code: "bv", name: "Bouvet Island" },
    ProviderProxyLocation { code: "bw", name: "Botswana" },
    ProviderProxyLocation { code: "by", name: "Belarus" },
    ProviderProxyLocation { code: "bz", name: "Belize" },
    ProviderProxyLocation { code: "ca", name: "Canada" },
    ProviderProxyLocation { code: "cc", name: "Cocos (Keeling) Islands" },
    ProviderProxyLocation { code: "cd", name: "Democratic Republic of the Congo" },
    ProviderProxyLocation { code: "cf", name: "Central African Republic" },
    ProviderProxyLocation { code: "cg", name: "Republic of the Congo" },
    ProviderProxyLocation { code: "ch", name: "Switzerland" },
    ProviderProxyLocation { code: "ck", name: "Cook Islands" },
    ProviderProxyLocation { code: "cl", name: "Chile" },
    ProviderProxyLocation { code: "cm", name: "Cameroon" },
    ProviderProxyLocation { code: "co", name: "Colombia" },
    ProviderProxyLocation { code: "cr", name: "Costa Rica" },
    ProviderProxyLocation { code: "cs", name: "Serbia and Montenegro" },
    ProviderProxyLocation { code: "cu", name: "Cuba" },
    ProviderProxyLocation { code: "cv", name: "Cape Verde" },
    ProviderProxyLocation { code: "cw", name: "Curaçao" },
    ProviderProxyLocation { code: "cx", name: "Christmas Island" },
    ProviderProxyLocation { code: "cy", name: "Cyprus" },
    ProviderProxyLocation { code: "cz", name: "Czech Republic" },
    ProviderProxyLocation { code: "de", name: "Germany" },
    ProviderProxyLocation { code: "dj", name: "Djibouti" },
    ProviderProxyLocation { code: "dk", name: "Denmark" },
    ProviderProxyLocation { code: "dm", name: "Dominica" },
    ProviderProxyLocation { code: "do", name: "Dominican Republic" },
    ProviderProxyLocation { code: "dz", name: "Algeria" },
    ProviderProxyLocation { code: "ec", name: "Ecuador" },
    ProviderProxyLocation { code: "ee", name: "Estonia" },
    ProviderProxyLocation { code: "eg", name: "Egypt" },
    ProviderProxyLocation { code: "eh", name: "Western Sahara" },
    ProviderProxyLocation { code: "er", name: "Eritrea" },
    ProviderProxyLocation { code: "es", name: "Spain" },
    ProviderProxyLocation { code: "et", name: "Ethiopia" },
    ProviderProxyLocation { code: "fi", name: "Finland" },
    ProviderProxyLocation { code: "fj", name: "Fiji" },
    ProviderProxyLocation { code: "fk", name: "Falkland Islands" },
    ProviderProxyLocation { code: "fm", name: "Micronesia" },
    ProviderProxyLocation { code: "fo", name: "Faroe Islands" },
    ProviderProxyLocation { code: "fr", name: "France" },
    ProviderProxyLocation { code: "ga", name: "Gabon" },
    ProviderProxyLocation { code: "gd", name: "Grenada" },
    ProviderProxyLocation { code: "ge", name: "Georgia" },
    ProviderProxyLocation { code: "gf", name: "French Guiana" },
    ProviderProxyLocation { code: "gg", name: "Guernsey" },
    ProviderProxyLocation { code: "gh", name: "Ghana" },
    ProviderProxyLocation { code: "gi", name: "Gibraltar" },
    ProviderProxyLocation { code: "gl", name: "Greenland" },
    ProviderProxyLocation { code: "gm", name: "Gambia" },
    ProviderProxyLocation { code: "gn", name: "Guinea" },
    ProviderProxyLocation { code: "gp", name: "Guadeloupe" },
    ProviderProxyLocation { code: "gq", name: "Equatorial Guinea" },
    ProviderProxyLocation { code: "gr", name: "Greece" },
    ProviderProxyLocation { code: "gs", name: "South Georgia & South Sandwich Islands" },
    ProviderProxyLocation { code: "gt", name: "Guatemala" },
    ProviderProxyLocation { code: "gu", name: "Guam" },
    ProviderProxyLocation { code: "gw", name: "Guinea-Bissau" },
    ProviderProxyLocation { code: "gy", name: "Guyana" },
    ProviderProxyLocation { code: "hk", name: "Hong Kong" },
    ProviderProxyLocation { code: "hm", name: "Heard Island & McDonald Islands" },
    ProviderProxyLocation { code: "hn", name: "Honduras" },
    ProviderProxyLocation { code: "hr", name: "Croatia" },
    ProviderProxyLocation { code: "ht", name: "Haiti" },
    ProviderProxyLocation { code: "hu", name: "Hungary" },
    ProviderProxyLocation { code: "id", name: "Indonesia" },
    ProviderProxyLocation { code: "ie", name: "Ireland" },
    ProviderProxyLocation { code: "il", name: "Israel" },
    ProviderProxyLocation { code: "im", name: "Isle of Man" },
    ProviderProxyLocation { code: "in", name: "India" },
    ProviderProxyLocation { code: "iq", name: "Iraq" },
    ProviderProxyLocation { code: "ir", name: "Iran" },
    ProviderProxyLocation { code: "is", name: "Iceland" },
    ProviderProxyLocation { code: "it", name: "Italy" },
    ProviderProxyLocation { code: "je", name: "Jersey" },
    ProviderProxyLocation { code: "jm", name: "Jamaica" },
    ProviderProxyLocation { code: "jo", name: "Jordan" },
    ProviderProxyLocation { code: "jp", name: "Japan" },
    ProviderProxyLocation { code: "ke", name: "Kenya" },
    ProviderProxyLocation { code: "kg", name: "Kyrgyzstan" },
    ProviderProxyLocation { code: "kh", name: "Cambodia" },
    ProviderProxyLocation { code: "ki", name: "Kiribati" },
    ProviderProxyLocation { code: "km", name: "Comoros" },
    ProviderProxyLocation { code: "kn", name: "Saint Kitts & Nevis" },
    ProviderProxyLocation { code: "kp", name: "North Korea" },
    ProviderProxyLocation { code: "kr", name: "South Korea" },
    ProviderProxyLocation { code: "kw", name: "Kuwait" },
    ProviderProxyLocation { code: "ky", name: "Cayman Islands" },
    ProviderProxyLocation { code: "kz", name: "Kazakhstan" },
    ProviderProxyLocation { code: "la", name: "Laos" },
    ProviderProxyLocation { code: "lb", name: "Lebanon" },
    ProviderProxyLocation { code: "lc", name: "Saint Lucia" },
    ProviderProxyLocation { code: "li", name: "Liechtenstein" },
    ProviderProxyLocation { code: "lk", name: "Sri Lanka" },
    ProviderProxyLocation { code: "lr", name: "Liberia" },
    ProviderProxyLocation { code: "ls", name: "Lesotho" },
    ProviderProxyLocation { code: "lt", name: "Lithuania" },
    ProviderProxyLocation { code: "lu", name: "Luxembourg" },
    ProviderProxyLocation { code: "lv", name: "Latvia" },
    ProviderProxyLocation { code: "ly", name: "Libya" },
    ProviderProxyLocation { code: "ma", name: "Morocco" },
    ProviderProxyLocation { code: "mc", name: "Monaco" },
    ProviderProxyLocation { code: "md", name: "Moldova" },
    ProviderProxyLocation { code: "me", name: "Montenegro" },
    ProviderProxyLocation { code: "mf", name: "Saint Martin" },
    ProviderProxyLocation { code: "mg", name: "Madagascar" },
    ProviderProxyLocation { code: "mh", name: "Marshall Islands" },
    ProviderProxyLocation { code: "mk", name: "North Macedonia" },
    ProviderProxyLocation { code: "ml", name: "Mali" },
    ProviderProxyLocation { code: "mm", name: "Myanmar" },
    ProviderProxyLocation { code: "mn", name: "Mongolia" },
    ProviderProxyLocation { code: "mo", name: "Macau" },
    ProviderProxyLocation { code: "mp", name: "Northern Mariana Islands" },
    ProviderProxyLocation { code: "mq", name: "Martinique" },
    ProviderProxyLocation { code: "mr", name: "Mauritania" },
    ProviderProxyLocation { code: "ms", name: "Montserrat" },
    ProviderProxyLocation { code: "mt", name: "Malta" },
    ProviderProxyLocation { code: "mu", name: "Mauritius" },
    ProviderProxyLocation { code: "mv", name: "Maldives" },
    ProviderProxyLocation { code: "mw", name: "Malawi" },
    ProviderProxyLocation { code: "mx", name: "Mexico" },
    ProviderProxyLocation { code: "my", name: "Malaysia" },
    ProviderProxyLocation { code: "mz", name: "Mozambique" },
    ProviderProxyLocation { code: "na", name: "Namibia" },
    ProviderProxyLocation { code: "nc", name: "New Caledonia" },
    ProviderProxyLocation { code: "ne", name: "Niger" },
    ProviderProxyLocation { code: "nf", name: "Norfolk Island" },
    ProviderProxyLocation { code: "ng", name: "Nigeria" },
    ProviderProxyLocation { code: "ni", name: "Nicaragua" },
    ProviderProxyLocation { code: "nl", name: "Netherlands" },
    ProviderProxyLocation { code: "no", name: "Norway" },
    ProviderProxyLocation { code: "np", name: "Nepal" },
    ProviderProxyLocation { code: "nr", name: "Nauru" },
    ProviderProxyLocation { code: "nu", name: "Niue" },
    ProviderProxyLocation { code: "nz", name: "New Zealand" },
    ProviderProxyLocation { code: "om", name: "Oman" },
    ProviderProxyLocation { code: "pa", name: "Panama" },
    ProviderProxyLocation { code: "pe", name: "Peru" },
    ProviderProxyLocation { code: "pf", name: "French Polynesia" },
    ProviderProxyLocation { code: "pg", name: "Papua New Guinea" },
    ProviderProxyLocation { code: "ph", name: "Philippines" },
    ProviderProxyLocation { code: "pk", name: "Pakistan" },
    ProviderProxyLocation { code: "pl", name: "Poland" },
    ProviderProxyLocation { code: "pm", name: "Saint Pierre & Miquelon" },
    ProviderProxyLocation { code: "pn", name: "Pitcairn Islands" },
    ProviderProxyLocation { code: "pr", name: "Puerto Rico" },
    ProviderProxyLocation { code: "ps", name: "Palestine" },
    ProviderProxyLocation { code: "pt", name: "Portugal" },
    ProviderProxyLocation { code: "pw", name: "Palau" },
    ProviderProxyLocation { code: "py", name: "Paraguay" },
    ProviderProxyLocation { code: "qa", name: "Qatar" },
    ProviderProxyLocation { code: "re", name: "Réunion" },
    ProviderProxyLocation { code: "ro", name: "Romania" },
    ProviderProxyLocation { code: "rs", name: "Serbia" },
    ProviderProxyLocation { code: "ru", name: "Russia" },
    ProviderProxyLocation { code: "rw", name: "Rwanda" },
    ProviderProxyLocation { code: "sa", name: "Saudi Arabia" },
    ProviderProxyLocation { code: "sb", name: "Solomon Islands" },
    ProviderProxyLocation { code: "sc", name: "Seychelles" },
    ProviderProxyLocation { code: "sd", name: "Sudan" },
    ProviderProxyLocation { code: "se", name: "Sweden" },
    ProviderProxyLocation { code: "sg", name: "Singapore" },
    ProviderProxyLocation { code: "sh", name: "Saint Helena" },
    ProviderProxyLocation { code: "si", name: "Slovenia" },
    ProviderProxyLocation { code: "sj", name: "Svalbard & Jan Mayen" },
    ProviderProxyLocation { code: "sk", name: "Slovakia" },
    ProviderProxyLocation { code: "sl", name: "Sierra Leone" },
    ProviderProxyLocation { code: "sm", name: "San Marino" },
    ProviderProxyLocation { code: "sn", name: "Senegal" },
    ProviderProxyLocation { code: "so", name: "Somalia" },
    ProviderProxyLocation { code: "sr", name: "Suriname" },
    ProviderProxyLocation { code: "ss", name: "South Sudan" },
    ProviderProxyLocation { code: "st", name: "São Tomé & Príncipe" },
    ProviderProxyLocation { code: "sv", name: "El Salvador" },
    ProviderProxyLocation { code: "sx", name: "Sint Maarten" },
    ProviderProxyLocation { code: "sy", name: "Syria" },
    ProviderProxyLocation { code: "sz", name: "Eswatini" },
    ProviderProxyLocation { code: "tc", name: "Turks & Caicos Islands" },
    ProviderProxyLocation { code: "td", name: "Chad" },
    ProviderProxyLocation { code: "tf", name: "French Southern Territories" },
    ProviderProxyLocation { code: "tg", name: "Togo" },
    ProviderProxyLocation { code: "th", name: "Thailand" },
    ProviderProxyLocation { code: "tj", name: "Tajikistan" },
    ProviderProxyLocation { code: "tk", name: "Tokelau" },
    ProviderProxyLocation { code: "tl", name: "Timor-Leste" },
    ProviderProxyLocation { code: "tm", name: "Turkmenistan" },
    ProviderProxyLocation { code: "tn", name: "Tunisia" },
    ProviderProxyLocation { code: "to", name: "Tonga" },
    ProviderProxyLocation { code: "tr", name: "Türkiye" },
    ProviderProxyLocation { code: "tt", name: "Trinidad & Tobago" },
    ProviderProxyLocation { code: "tv", name: "Tuvalu" },
    ProviderProxyLocation { code: "tw", name: "Taiwan" },
    ProviderProxyLocation { code: "tz", name: "Tanzania" },
    ProviderProxyLocation { code: "ua", name: "Ukraine" },
    ProviderProxyLocation { code: "ug", name: "Uganda" },
    ProviderProxyLocation { code: "uk", name: "United Kingdom" },
    ProviderProxyLocation { code: "us", name: "United States" },
    ProviderProxyLocation { code: "uy", name: "Uruguay" },
    ProviderProxyLocation { code: "uz", name: "Uzbekistan" },
    ProviderProxyLocation { code: "va", name: "Vatican City" },
    ProviderProxyLocation { code: "vc", name: "Saint Vincent & the Grenadines" },
    ProviderProxyLocation { code: "ve", name: "Venezuela" },
    ProviderProxyLocation { code: "vg", name: "British Virgin Islands" },
    ProviderProxyLocation { code: "vi", name: "U.S. Virgin Islands" },
    ProviderProxyLocation { code: "vn", name: "Vietnam" },
    ProviderProxyLocation { code: "vu", name: "Vanuatu" },
    ProviderProxyLocation { code: "wf", name: "Wallis & Futuna" },
    ProviderProxyLocation { code: "ws", name: "Samoa" },
    ProviderProxyLocation { code: "xk", name: "Kosovo" },
    ProviderProxyLocation { code: "ye", name: "Yemen" },
    ProviderProxyLocation { code: "yt", name: "Mayotte" },
    ProviderProxyLocation { code: "za", name: "South Africa" },
    ProviderProxyLocation { code: "zm", name: "Zambia" },
    ProviderProxyLocation { code: "zw", name: "Zimbabwe" },
];

pub const fn proxy_locations() -> &'static [ProviderProxyLocation] {
    BROWSER_USE_PROXY_LOCATIONS
}

pub fn is_proxy_location(code: &str) -> bool {
    BROWSER_USE_PROXY_LOCATIONS.iter().any(|location| location.code.eq_ignore_ascii_case(code))
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;

    #[test]
    fn test_group_proxy_schema_snapshot_is_complete_unique_and_provider_specific() {
        assert_eq!(BROWSER_USE_PROXY_SCHEMA_SNAPSHOT, "browser-use-api-v3@2026-09-04");
        assert_eq!(proxy_locations().len(), 247);
        let unique = proxy_locations().iter().map(|location| location.code).collect::<BTreeSet<_>>();
        assert_eq!(unique.len(), proxy_locations().len());
        for representative in ["us", "in", "de", "jp", "uk", "xk", "an", "cs"] {
            assert!(is_proxy_location(representative), "missing {representative}");
        }
        // Browser Use's enum is not generic ISO-3166: use its `uk` alias and exact omissions.
        for unsupported in ["gb", "cn", "ax", "io", "um"] {
            assert!(!is_proxy_location(unsupported), "unexpected {unsupported}");
        }
    }
}
